#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         3
bspc config window_gap          12

bspc config top_padding 0

bspc config focused_border_color "#cae7c1"
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on

~/.fehbg &
~/.config/polybar/launch.sh &
picom &
